from contextlib import asynccontextmanager
from fastapi import FastAPI, Depends
from pydantic import BaseModel
from sqlalchemy import select

from sqlalchemy.ext.asyncio import AsyncSession, create_async_engine, async_sessionmaker
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

DATABASE_URL = "sqlite+aiosqlite:///factory.db" 

engine = create_async_engine(DATABASE_URL, echo=True)

SessionLocal = async_sessionmaker(bind=engine, _class= AsyncSession, expire_on_commit=False) #_class is used to specify the class to be used for the session, in this case AsyncSession 

class Base(DeclarativeBase):
    pass

class Prediction(Base):

    __tablename__= "predictions"

    id:Mapped[int] = mapped_column(primary_key=True, autoincrement=True)

    machine_id: Mapped[int] = mapped_column(nullable=False)
    prediction: Mapped[str] = mapped_column(nullable=False)

class PredictionCreate(BaseModel):
    machine_id: int
    prediction: str


# what these two classes do is to create the database and the table in the database, and to create a session to interact with the database predictioncreate is a pydantic model that is used to validate the data that is sent to the API when creating a new prediction, it has the same fields as the Prediction model but without the id field because it will be generated automatically by the database 


@asynccontextmanager# this is used to create a context manager that can be used to create a session and close it after the operation is done

async def lifespan(app: FastAPI):
    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)
    yield
    await engine.dispose() #it is used to close the connection to the database when the application is shut down

app= FastAPI(lifespan=lifespan)

async def get_db():
    async with SessionLocal() as session: 
        yield session

        #what sessionlocal is doing is creating a new session for each request and closing it after the request is done, this is important to avoid having too many open connections to the database and to ensure that the data is consistent when multiple requests are made at the same time

@app.post("/predictions")

async def create_prediction(
    prediction : PredictionCreate, db: AsyncSession = Depends(get_db)

):
    row = Prediction(
        machine_id=prediction.machine_id, 
        prediction=prediction.prediction
                     )
    
    db.add(row)
    await db.commit()
    await db.refresh(row) # this is used to refresh the instance of the prediction after it has been committed to the database, this is important to get the id of the prediction that was generated by the database

    return {"id": row.id, "machine_id": row.machine_id, "prediction": row.prediction}

@app.get("/predictions")

async def read_predictions(db: AsyncSession = Depends(get_db)):
    result = await db.execute(select(Prediction))
    predictions = result.scalars().all()  # list of Prediction objects

    return [
        {"id": p.id, "machine_id": p.machine_id, "prediction": p.prediction}
        for p in predictions
    ]